#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Petstore.v1/ && \
    dotnet build src/Petstore.v1/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Petstore.v1/Petstore.v1.csproj --launch-profile web"
