/*
 * Swagger Petstore
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using PetstoreV1.Client;
using PetstoreV1.Api;
// uncomment below to import models
//using PetstoreV1.Model;

namespace PetstoreV1.Test.Api
{
    /// <summary>
    ///  Class for testing PetsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PetsApiTests : IDisposable
    {
        private PetsApi instance;

        public PetsApiTests()
        {
            instance = new PetsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PetsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PetsApi
            //Assert.IsType<PetsApi>(instance);
        }

        /// <summary>
        /// Test CreatePets
        /// </summary>
        [Fact]
        public void CreatePetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.CreatePets();
        }

        /// <summary>
        /// Test ListPets
        /// </summary>
        [Fact]
        public void ListPetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //var response = instance.ListPets(limit);
            //Assert.IsType<List<Pet>>(response);
        }

        /// <summary>
        /// Test ShowPetById
        /// </summary>
        [Fact]
        public void ShowPetByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string petId = null;
            //var response = instance.ShowPetById(petId);
            //Assert.IsType<Pet>(response);
        }
    }
}
