:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\Petstore.v2
dotnet build src\Petstore.v2
echo Now, run the following to start the project: dotnet run -p src\Petstore.v2\Petstore.v2.csproj --launch-profile web.
echo.
