/*
 * Swagger Petstore
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PetstoreV2.Api;
using PetstoreV2.Model;
using PetstoreV2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PetstoreV2.Test.Model
{
    /// <summary>
    ///  Class for testing Pet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Pet
        //private Pet instance;

        public PetTests()
        {
            // TODO uncomment below to create an instance of Pet
            //instance = new Pet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Pet
        /// </summary>
        [Fact]
        public void PetInstanceTest()
        {
            // TODO uncomment below to test "IsType" Pet
            //Assert.IsType<Pet>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Fact]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }
        /// <summary>
        /// Test the property 'OwnerName'
        /// </summary>
        [Fact]
        public void OwnerNameTest()
        {
            // TODO unit test for the property 'OwnerName'
        }

    }

}
